-- Migração da Base de Dados Firebird para Integração Ponto Control iD
-- Banco de Dados: D:\OneDrive\DADOS\DUSUCO\DADOS.FDB

-- 1. Campos complementares em TB_PONTO_RELOGIO
ALTER TABLE TB_PONTO_RELOGIO ADD PRE_PORTA INTEGER DEFAULT 80;
ALTER TABLE TB_PONTO_RELOGIO ADD PRE_USAR_SSL CHAR(1) DEFAULT 'N';
ALTER TABLE TB_PONTO_RELOGIO ADD PRE_MODELO VARCHAR(40) DEFAULT 'IDCLASS';
ALTER TABLE TB_PONTO_RELOGIO ADD PRE_MODO_COLETA VARCHAR(20) DEFAULT 'API';
ALTER TABLE TB_PONTO_RELOGIO ADD PRE_ULTIMA_COLETA TIMESTAMP;
ALTER TABLE TB_PONTO_RELOGIO ADD PRE_SERIAL VARCHAR(50);
ALTER TABLE TB_PONTO_RELOGIO ADD PRE_VERSAO_FW VARCHAR(50);
ALTER TABLE TB_PONTO_RELOGIO ADD PRE_ATIVO CHAR(1) DEFAULT 'S';
COMMIT;

-- 2. Campos complementares em TB_PONTO_MARCACAO
ALTER TABLE TB_PONTO_MARCACAO ADD PMA_NSR BIGINT;
ALTER TABLE TB_PONTO_MARCACAO ADD PMA_PIS VARCHAR(15);
ALTER TABLE TB_PONTO_MARCACAO ADD PMA_CPF VARCHAR(14);
ALTER TABLE TB_PONTO_MARCACAO ADD PMA_TIPO_BATIDA VARCHAR(20);
ALTER TABLE TB_PONTO_MARCACAO ADD PMA_TIPO_IDENTIFICACAO VARCHAR(30);
ALTER TABLE TB_PONTO_MARCACAO ADD PMA_EXPORTADO CHAR(1) DEFAULT 'N';
COMMIT;

-- 3. Campos complementares em TB_COLABORADOR
ALTER TABLE TB_COLABORADOR ADD COL_SINCRONIZADO_RELOGIO CHAR(1) DEFAULT 'N';
ALTER TABLE TB_COLABORADOR ADD COL_ULTIMA_SINCRONIZACAO TIMESTAMP;
COMMIT;

-- 4. Triggers para geração automática de Chave Primária
SET TERM ^ ;

CREATE OR ALTER TRIGGER T_PONTO_RELOGIO_BI FOR TB_PONTO_RELOGIO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.PRE_ID IS NULL OR NEW.PRE_ID <= 0) THEN
    NEW.PRE_ID = GEN_ID(GEN_PONTO_RELOGIO, 1);
  IF (NEW.PRE_PORTA IS NULL OR NEW.PRE_PORTA <= 0) THEN
    NEW.PRE_PORTA = 80;
  IF (NEW.PRE_USAR_SSL IS NULL) THEN
    NEW.PRE_USAR_SSL = 'N';
  IF (NEW.PRE_STATUS IS NULL) THEN
    NEW.PRE_STATUS = 'A';
  IF (NEW.PRE_ATIVO IS NULL) THEN
    NEW.PRE_ATIVO = 'S';
  IF (NEW.PRE_ULTIMO_LOG_ID IS NULL) THEN
    NEW.PRE_ULTIMO_LOG_ID = 0;
END^

CREATE OR ALTER TRIGGER T_PONTO_MARCACAO_BI FOR TB_PONTO_MARCACAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.PMA_ID IS NULL OR NEW.PMA_ID <= 0) THEN
    NEW.PMA_ID = GEN_ID(GEN_PONTO_MARCACAO, 1);
  IF (NEW.PMA_EVENTO IS NULL) THEN
    NEW.PMA_EVENTO = 7;
  IF (NEW.PMA_ORIGEM IS NULL) THEN
    NEW.PMA_ORIGEM = 'C';
  IF (NEW.PMA_EXPORTADO IS NULL) THEN
    NEW.PMA_EXPORTADO = 'N';
END^

SET TERM ; ^
COMMIT;

-- 5. Índices de Otimização e Prevenção de Duplicidades
CREATE INDEX IDX_PMA_DATA_HORA ON TB_PONTO_MARCACAO (PMA_DATA_HORA);
CREATE INDEX IDX_PMA_PESSOA ON TB_PONTO_MARCACAO (PMA_PESSOA);
COMMIT;
