-- Script de Migração: Módulo de Horários, Ocorrências e Espelho de Ponto
-- Banco de Dados: D:\OneDrive\DADOS\DUSUCO\DADOS.FDB

CREATE GENERATOR GEN_PONTO_HORARIO;
CREATE GENERATOR GEN_PONTO_JUSTIFICATIVA;

CREATE TABLE TB_PONTO_HORARIO (
    HOR_ID INTEGER NOT NULL,
    HOR_DESCRICAO VARCHAR(60) NOT NULL,
    HOR_ENTRADA_1 TIME,
    HOR_SAIDA_1 TIME,
    HOR_ENTRADA_2 TIME,
    HOR_SAIDA_2 TIME,
    HOR_TOLERANCIA_MIN INTEGER DEFAULT 10,
    HOR_CARGA_DIARIA_MIN INTEGER DEFAULT 528,
    HOR_COMPENSA_SABADO CHAR(1) DEFAULT 'S',
    HOR_TRABALHA_SABADO CHAR(1) DEFAULT 'N',
    HOR_SAB_ENTRADA_1 TIME,
    HOR_SAB_SAIDA_1 TIME,
    HOR_ATIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT PK_TB_PONTO_HORARIO PRIMARY KEY (HOR_ID)
);

CREATE TABLE TB_PONTO_JUSTIFICATIVA (
    JUS_ID INTEGER NOT NULL,
    JUS_PESSOA INTEGER NOT NULL,
    JUS_DATA DATE NOT NULL,
    JUS_TIPO VARCHAR(30) NOT NULL,
    JUS_MOTIVO VARCHAR(250),
    JUS_ABONO_MINUTOS INTEGER DEFAULT 0,
    JUS_CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_PONTO_JUSTIFICATIVA PRIMARY KEY (JUS_ID)
);

ALTER TABLE TB_COLABORADOR ADD COL_HORARIO INTEGER;

SET TERM ^ ;

CREATE OR ALTER TRIGGER T_PONTO_HORARIO_BI FOR TB_PONTO_HORARIO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.HOR_ID IS NULL OR NEW.HOR_ID <= 0) THEN
    NEW.HOR_ID = GEN_ID(GEN_PONTO_HORARIO, 1);
  IF (NEW.HOR_ATIVO IS NULL) THEN
    NEW.HOR_ATIVO = 'S';
  IF (NEW.HOR_TOLERANCIA_MIN IS NULL) THEN
    NEW.HOR_TOLERANCIA_MIN = 10;
  IF (NEW.HOR_CARGA_DIARIA_MIN IS NULL) THEN
    NEW.HOR_CARGA_DIARIA_MIN = 528;
END^

CREATE OR ALTER TRIGGER T_PONTO_JUSTIFICATIVA_BI FOR TB_PONTO_JUSTIFICATIVA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.JUS_ID IS NULL OR NEW.JUS_ID <= 0) THEN
    NEW.JUS_ID = GEN_ID(GEN_PONTO_JUSTIFICATIVA, 1);
  IF (NEW.JUS_ABONO_MINUTOS IS NULL) THEN
    NEW.JUS_ABONO_MINUTOS = 0;
END^

SET TERM ; ^

INSERT INTO TB_PONTO_HORARIO (
    HOR_ID, HOR_DESCRICAO, HOR_ENTRADA_1, HOR_SAIDA_1, HOR_ENTRADA_2, HOR_SAIDA_2,
    HOR_TOLERANCIA_MIN, HOR_CARGA_DIARIA_MIN, HOR_COMPENSA_SABADO, HOR_TRABALHA_SABADO, HOR_ATIVO
) VALUES (
    1, 'Comercial 44h (08:00 - 12:00 / 13:12 - 18:00)', '08:00:00', '12:00:00', '13:12:00', '18:00:00',
    10, 528, 'S', 'N', 'S'
);

INSERT INTO TB_PONTO_HORARIO (
    HOR_ID, HOR_DESCRICAO, HOR_ENTRADA_1, HOR_SAIDA_1, HOR_ENTRADA_2, HOR_SAIDA_2,
    HOR_TOLERANCIA_MIN, HOR_CARGA_DIARIA_MIN, HOR_COMPENSA_SABADO, HOR_TRABALHA_SABADO,
    HOR_SAB_ENTRADA_1, HOR_SAB_SAIDA_1, HOR_ATIVO
) VALUES (
    2, 'Comercial 44h com Sabado (08:00 - 12:00 / 14:00 - 18:00 + Sab 08:00 - 12:00)', '08:00:00', '12:00:00', '14:00:00', '18:00:00',
    10, 480, 'N', 'S', '08:00:00', '12:00:00', 'S'
);

COMMIT;
