UPDATE TB_PONTO_RELOGIO 
SET PRE_IP = '192.168.10.99', 
    PRE_PORTA = 443, 
    PRE_USAR_SSL = 'S'
WHERE PRE_ID = 1;
COMMIT;
SELECT PRE_ID, PRE_NOME, PRE_IP, PRE_PORTA, PRE_USAR_SSL FROM TB_PONTO_RELOGIO;
